try{
    let a=10;
    //let b=20;
    let res = a+b;
    console.log("Result: " + res);
    
}
/*catch(error){
    console.error("Error name: " +error.name);
    console.error("Error message: " + error.message)
}*/
finally{
    console.log("finally block is executed")
}